//agregar una funcion con la instruccion function
function sumanumeros() {
    //declarar las variables
    let num1 = 5;
    let num2 = 10;
    let suma = 0;

    suma = num1 + num2;
//se hace el proceso y se imprime
    document.write(num1 + num2);
    //hacer el proceso y despues lo imprime en las configuraciones del navegador
    console.log(suma);
    //console.log("cualquier cosa");

alert("la suma de dos numeros es:" + suma);
}